In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [4]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [5]:
# Broadcasting

In [6]:
df["Salary"] = df["Salary"] + 5000
df

      Name   Age Department   Salary
0    Alice  25.0         HR  55000.0
1      Bob  30.0         IT  65000.0
2  Charlie  35.0    Finance  75000.0
3    David   NaN         IT  67000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  55000.0

In [7]:
# RENAME column

In [9]:
df.rename(columns = {"Department":"Dept"}, inplace = True)

In [10]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [12]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [14]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [15]:
df["Hiked Salary"] = df["Salary"] * 2

In [16]:
df

      Name   Age     Dept   Salary  Hiked Salary
0    Alice  25.0       HR  55000.0      110000.0
1      Bob  30.0       IT  65000.0      130000.0
2  Charlie  35.0  Finance  75000.0      150000.0
3    David   NaN       IT  67000.0      134000.0
4      Eve  29.0       HR      NaN           NaN
5    Alice  25.0       HR  55000.0      110000.0