In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [3]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [6]:
df.isnull().sum()

Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [7]:
df.dropna()

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
5    Alice  25.0         HR  50000.0

In [9]:
df.dropna(how ="any") # any row that had any null value

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
5    Alice  25.0         HR  50000.0

In [10]:
df.dropna(how ="all") # if all the values in any row are null then we drop that row

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [11]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [12]:
df["Salary"].fillna(df["Salary"].median())

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4    60000.0
5    50000.0
Name: Salary, dtype: float64

In [13]:
# forward fill

In [15]:
df["Age"].fillna(method = "ffill")

/var/folders/tn/j1nvqf4j0nv2kxw9fyc1m1bm0000gn/T/ipykernel_20030/544980945.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [16]:
# backward fill

In [17]:
df["Age"].fillna(method = "bfill")

/var/folders/tn/j1nvqf4j0nv2kxw9fyc1m1bm0000gn/T/ipykernel_20030/3026805218.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [18]:
df["Name"].replace("Charlie","Rose")

0    Alice
1      Bob
2     Rose
3    David
4      Eve
5    Alice
Name: Name, dtype: object

In [19]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [20]:
df["Name"] = df["Name"].replace("Charlie","Rose")

In [21]:
df

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0
2   Rose  35.0    Finance  70000.0
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0