In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0


In Pandas, we combine datasets using:

* `pd.merge()` → SQL-style joins (most common)
* `df.join()` → simpler index-based join
* `pd.concat()` → stacking (not SQL join)

Today we’ll focus on **merge + join types**:

* Inner
* Left
* Right
* Outer

---

# 🔹 1️⃣ Sample DataFrames

Let’s create two small tables.

```python
import pandas as pd

df_students = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Rahul", "Aman", "Priya", "Sneha"]
})

df_marks = pd.DataFrame({
    "id": [1, 2, 4, 5],
    "marks": [85, 90, 88, 75]
})

print(df_students)
print(df_marks)
```

### 🧾 Students Table

| id | name  |
| -- | ----- |
| 1  | Rahul |
| 2  | Aman  |
| 3  | Priya |
| 4  | Sneha |

### 🧾 Marks Table

| id | marks |
| -- | ----- |
| 1  | 85    |
| 2  | 90    |
| 4  | 88    |
| 5  | 75    |

Notice:

* ID 3 is missing in marks
* ID 5 is missing in students

Now let's understand joins.

---

# 🔹 2️⃣ INNER JOIN (Default)

👉 Only keeps common values in both tables.

```python
pd.merge(df_students, df_marks, on="id", how="inner")
```

### Result:

| id | name  | marks |
| -- | ----- | ----- |
| 1  | Rahul | 85    |
| 2  | Aman  | 90    |
| 4  | Sneha | 88    |

✔ Keeps only ids: 1,2,4
❌ Removes id 3 and 5

👉 Think: **Intersection**

---

# 🔹 3️⃣ LEFT JOIN

👉 Keeps ALL rows from left table
👉 Matches from right table
👉 If no match → NaN

```python
pd.merge(df_students, df_marks, on="id", how="left")
```

### Result:

| id | name  | marks |
| -- | ----- | ----- |
| 1  | Rahul | 85    |
| 2  | Aman  | 90    |
| 3  | Priya | NaN   |
| 4  | Sneha | 88    |

✔ All students kept
❌ id 3 has no marks → NaN

👉 Think: **"Left table is boss"**

---

# 🔹 4️⃣ RIGHT JOIN

👉 Keeps ALL rows from right table
👉 Matches from left
👉 Missing values become NaN

```python
pd.merge(df_students, df_marks, on="id", how="right")
```

### Result:

| id | name  | marks |
| -- | ----- | ----- |
| 1  | Rahul | 85    |
| 2  | Aman  | 90    |
| 4  | Sneha | 88    |
| 5  | NaN   | 75    |

✔ All marks kept
❌ id 5 has no student → NaN

👉 Think: **"Right table is boss"**

---

# 🔹 5️⃣ OUTER JOIN

👉 Keeps ALL rows from both tables
👉 Missing values become NaN

```python
pd.merge(df_students, df_marks, on="id", how="outer")
```

### Result:

| id | name  | marks |
| -- | ----- | ----- |
| 1  | Rahul | 85    |
| 2  | Aman  | 90    |
| 3  | Priya | NaN   |
| 4  | Sneha | 88    |
| 5  | NaN   | 75    |

✔ Keeps everything
👉 Think: **Union**

---

# 🔹 Visual Understanding (VERY IMPORTANT)

## INNER JOIN

```
Students ∩ Marks
```

## LEFT JOIN

```
All Students + Matching Marks
```

## RIGHT JOIN

```
All Marks + Matching Students
```

## OUTER JOIN

```
Students ∪ Marks
```

---

# 🔹 6️⃣ What is `.join()` then?

`.join()` works mostly on index.

Example:

```python
df_students.set_index("id").join(df_marks.set_index("id"), how="inner")
```

Same result as merge.

👉 Difference:

| merge()          | join()         |
| ---------------- | -------------- |
| Works on columns | Works on index |
| More flexible    | Simpler syntax |

In interviews → **merge is more important**

---

# 🔹 7️⃣ Real World Example

Imagine:

* Table 1 → Users
* Table 2 → Orders

You want:

* Only users who ordered → INNER
* All users (even if no order) → LEFT
* All orders (even if deleted user) → RIGHT
* Full system data → OUTER

---

# 🔥 Interview Trick Question

Q: What is default join in pandas?
👉 `inner`

Q: What happens if no matching key?
👉 NaN (except inner)

In [9]:
# Joins and Merges

import pandas as pd

department_info = {
    "Department": ["HR", "IT", "Finance"],
    "Location": ["New York", "San Francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

  Department       Location Manager
0         HR       New York   Laura
1         IT  San Francisco   Steve
2    Finance        Chicago    Nina

In [11]:
# concat

In [12]:
pd.concat([df, df2])

      Name   Age Department   Salary       Location Manager
0    Alice  25.0         HR  50000.0            NaN     NaN
1      Bob  30.0         IT  60000.0            NaN     NaN
2  Charlie  35.0    Finance  70000.0            NaN     NaN
3    David   NaN         IT  62000.0            NaN     NaN
4      Eve  29.0         HR      NaN            NaN     NaN
5    Alice  25.0         HR  50000.0            NaN     NaN
0      NaN   NaN         HR      NaN       New York   Laura
1      NaN   NaN         IT      NaN  San Francisco   Steve
2      NaN   NaN    Finance      NaN        Chicago    Nina

In [13]:
pd.concat([df, df2], axis = 1)

      Name   Age Department   Salary Department       Location Manager
0    Alice  25.0         HR  50000.0         HR       New York   Laura
1      Bob  30.0         IT  60000.0         IT  San Francisco   Steve
2  Charlie  35.0    Finance  70000.0    Finance        Chicago    Nina
3    David   NaN         IT  62000.0        NaN            NaN     NaN
4      Eve  29.0         HR      NaN        NaN            NaN     NaN
5    Alice  25.0         HR  50000.0        NaN            NaN     NaN

In [14]:
pd.merge(df, df2, on = "Dpartment")

      Name   Age Department   Salary       Location Manager
0    Alice  25.0         HR  50000.0       New York   Laura
1      Bob  30.0         IT  60000.0  San Francisco   Steve
2  Charlie  35.0    Finance  70000.0        Chicago    Nina
3    David   NaN         IT  62000.0  San Francisco   Steve
4      Eve  29.0         HR      NaN       New York   Laura
5    Alice  25.0         HR  50000.0       New York   Laura