In [3]:
import pandas as pd
import numpy as np

In [4]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [5]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [6]:
df["Hiked Salary"] = df["Salary"] * 2
df

      Name   Age Department   Salary  Hiked Salary
0    Alice  25.0         HR  50000.0      100000.0
1      Bob  30.0         IT  60000.0      120000.0
2  Charlie  35.0    Finance  70000.0      140000.0
3    David   NaN         IT  62000.0      124000.0
4      Eve  29.0         HR      NaN           NaN
5    Alice  25.0         HR  50000.0      100000.0

In [14]:
df["Hiked Salary"] = df["Hiked Salary"].apply(lambda x: x / 5
if x > 100000.0 else x)
df

      Name   Age Department   Salary  Hiked Salary
0    Alice  25.0         HR  50000.0      100000.0
1      Bob  30.0         IT  60000.0       12000.0
2  Charlie  35.0    Finance  70000.0       14000.0
3    David   NaN         IT  62000.0       12400.0
4      Eve  29.0         HR      NaN           NaN
5    Alice  25.0         HR  50000.0      100000.0

In [15]:
#using str.split() ,we can split the string data

In [16]:
# apply and lambda

In [17]:
def multiplying_age(x):
    return x*2
df["Age"] = df["Age"].apply(multiplying_age)

In [18]:
df

      Name   Age Department   Salary  Hiked Salary
0    Alice  50.0         HR  50000.0      100000.0
1      Bob  60.0         IT  60000.0       12000.0
2  Charlie  70.0    Finance  70000.0       14000.0
3    David   NaN         IT  62000.0       12400.0
4      Eve  58.0         HR      NaN           NaN
5    Alice  50.0         HR  50000.0      100000.0

In [19]:
df["Age"] = df["Age"].apply(lambda x: x/2)

In [20]:
df

      Name   Age Department   Salary  Hiked Salary
0    Alice  25.0         HR  50000.0      100000.0
1      Bob  30.0         IT  60000.0       12000.0
2  Charlie  35.0    Finance  70000.0       14000.0
3    David   NaN         IT  62000.0       12400.0
4      Eve  29.0         HR      NaN           NaN
5    Alice  25.0         HR  50000.0      100000.0