In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("annual-enterprise-survey-2024-financial-year-provisional-size-bands.csv")

In [6]:
data.head()

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.shape

(21672, 16)

In [7]:
df = pd.DataFrame(data)

In [8]:
df.head()

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
data.info

<bound method DataFrame.info of        year industry_code_ANZSIC               industry_name_ANZSIC  \
0      2011                    A  Agriculture, Forestry and Fishing
1      2011                    A  Agriculture, Forestry and Fishing
2      2011                    A  Agriculture, Forestry and Fishing
3      2011                    A  Agriculture, Forestry and Fishing
4      2011                    A  Agriculture, Forestry and Fishing
...     ...                  ...                                ...
21667  2024                  all                     All Industries
21668  2024                  all                     All Industries
21669  2024                  all                     All Industries
21670  2024                  all                     All Industries
21671  2024                  all                     All Industries

        rme_size_grp                                         variable  \
0                a_0                                    Activity unit
1                a_0                           Rolling mean employees
2                a_0                          Salaries and wages paid
3                a_0  Sales, government funding, grants and subsidies
4                a_0                                     Total income
...              ...                                              ...
21667  j_Grand_Total                          Salaries and wages paid
21668  j_Grand_Total  Sales, government funding, grants and subsidies
21669  j_Grand_Total                                     Total assets
21670  j_Grand_Total                                Total expenditure
21671  j_Grand_Total                                     Total income

         value               unit  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0        46134              COUNT         NaN         NaN         NaN
1            0              COUNT         NaN         NaN         NaN
2          279  DOLLARS(millions)         NaN         NaN         NaN
3         8187  DOLLARS(millions)         NaN         NaN         NaN
4         8866  DOLLARS(millions)         NaN         NaN         NaN
...        ...                ...         ...         ...         ...
21667   157616  DOLLARS(millions)         NaN         NaN         NaN
21668   838626  DOLLARS(millions)         NaN         NaN         NaN
21669  2931807  DOLLARS(millions)         NaN         NaN         NaN
21670   856960  DOLLARS(millions)         NaN         NaN         NaN
21671   979594  DOLLARS(millions)         NaN         NaN         NaN

      Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15
0             NaN         NaN         NaN         NaN         NaN         NaN
1             NaN         NaN         NaN         NaN         NaN         NaN
2             NaN         NaN         NaN         NaN         NaN         NaN
3             NaN         NaN         NaN         NaN         NaN         NaN
4             NaN         NaN         NaN         NaN         NaN         NaN
...           ...         ...         ...         ...         ...         ...
21667         NaN         NaN         NaN         NaN         NaN         NaN
21668         NaN         NaN         NaN         NaN         NaN         NaN
21669         NaN         NaN         NaN         NaN         NaN         NaN
21670         NaN         NaN         NaN         NaN         NaN         NaN
21671         NaN         NaN         NaN         NaN         NaN         NaN

[21672 rows x 16 columns]>